apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 50-worker-enable-sssd-service
spec:
  config:
    ignition:
      version: 2.2.0
    systemd:
      units:
      - name: sssd.service
        enabled: true

